### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by bharatpaliwal-169** [MateDawid/DjangoVideoAnalyzer#1]
Hello @MateDawid  I'm  working on the project that uses webcam and detects the user pose , brother can u pls help me with how to access the webcam and capture the real-time frame from the webcam by using django and opencv 

Any lead could be helpful 

PS : I have explored a lot of google n stackoverflow but couldn't find any way , i am seekhing any lead from you coz u are workin so something like that 

Thanks in advance

**Comment by MateDawid** [comment]
Hello @bharatpaliwal-169

This video was really helpful about connection between Django and OpenCV library - https://www.youtube.com/watch?v=KUoNQ-44-1k

In videoanalyzer/videoanalyzer/video.py there's function **gen**, that is crucial to proper displaying of captured webcam image. 

`def gen(camera):`  
`if camera.get_frame() != 0:`      
`    while True:`         
`        frame = camera.get_frame() `           
`        yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')``

This function is used in videoanalyzer/main/views.py in **feed** function:

`@gzip.gzip_pagedef `
`feed(request):` 
 ...    
`cam = VideoCamera() `      
`return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")`

**Comment by bharatpaliwal-169** [comment]
Thanks brother for your suggestions .
